name: CI/CD with Docker

on:
  push:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run tests
        run: echo "tests"

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      - name: Try to print secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "The secret is: $MY_SECRET"
